baseURL = "https://daniel-zamo.github.io/notes/"
title = "@DZ Notes"
theme = ["github.com/McShelby/hugo-theme-relearn"]

defaultContentLanguage = "es"
languageCode = "es-es"

[languages]
  [languages.es]
    languageName = "Espa√±ol"
    contentDir = "content"
    weight = 1

[params]
  editURL = "https://github.com/daniel-zamo/notes/edit/main/content/"
  themeVariant = "relearn-dark"
 
  [params.author]
    name = "Daniel Zamo"

