baseURL = "https://daniel-zamo.github.io/notes/"
languageCode = "es-es"
title = "@DZ Notes"
theme = ["github.com/McShelby/hugo-theme-relearn"]

[outputs]
  home = ["HTML", "RSS", "SEARCH"]

[params]
  editURL = "https://github.com/daniel-zamo/notes/edit/main/content/"
  description = "Manual de operaciones y notas t√©cnicas"
  author = "Daniel Zamo"
  showBreadcrumbs = true
  themeVariant = "relearn-dark"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  style = "monokai"
