baseURL = "https://daniel-zamo.github.io/notes/"
languageCode = "es-es"
title = "@DZ Notes"
theme = ["github.com/McShelby/hugo-theme-relearn"]

# En la v9, eliminamos "SEARCH" para evitar el warning de formato no soportado
[outputs]
  home = ["HTML", "RSS"]

[params]
  editURL = "https://github.com/daniel-zamo/notes/edit/main/content/"
  showBreadcrumbs = true
  themeVariant = "relearn-dark"
#  themeVariant = [ "relearn-dark", ..., ... ]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    codeFences = true
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Vital para renderizar los iconos <i> de FontAwesome
    [markup.goldmark.parser.attribute]
      block = true   # Permite los atributos {class="..."} de la v9
      title = true
